### ISSUE TITLE
Instructions could be clearer, also can't compile 64 bit

### ISSUE THREAD

**Issue by C0rn3j** [kozec/dumbxinputemu#1]
So I figured I need to install a package that's named mingw-w64-gcc, on Arch at least.

Figured I have to run make in the root folder, which I did, which generated ./build/32/xinput*.dll

If I check the releases however, there's also a 64 folder with the 64 bit version of the dll(I assume) - how do I build that dll myself?

Also it'd probably be good to include link to the releases tab in the README.MD or at least mention it

**Comment by kozec** [comment]
There are any instructions? :)

To build 64 bit version, run `make 64bit`

**Comment by C0rn3j** [comment]
I think the instructions are fine as they are but I'd still add a link to the Releases as git noobs are not very aware of it. It'd make it more user friendly.

https://www.reddit.com/r/linux_gaming/comments/6rf8rk/wine_214_released/dl64js1/

**Comment by kozec** [comment]
I have to admit, this is one of those possibilities that just never occurred to me :D

Added link to release page right to fist sentence.

**Comment by C0rn3j** [comment]
https://www.reddit.com/r/linux_gaming/comments/6s35ba/xbox_360_controller_with_cemu_in_ubuntu/dl9ujqr/

Since the DLLs require to be overriden in winecfg, would you add that to the instructions?

**Comment by kozec** [comment]
> Since the DLLs require to be overriden in winecfg, would you add that to the instructions?

Added one. Hopefully, everyone knows what DLL override(s) in Wine are :)

**Comment by bryanwillis7** [comment]
No! I don't! Ugh tell me! :(

**Comment by C0rn3j** [comment]
@bryanwillis7 it's set in a menu in `winecfg`
