### ISSUE TITLE
Doesn't work for joydev devices

### ISSUE THREAD

**Issue by Benjamin-L** [kozec/dumbxinputemu#10]
It looks like this had previously been configured to ignore any joystick device containing the string `(js)` (dbc30fe07f945af43540be27f49a4bd5ebb9feb4). This works as intended, assuming that an evdev device for the same joystick actually exists, but if there is no evdev device then it will fail to detect the joystick at all. I'm not really sure how common that situation is, but I have been having issues with getting a joydev device, but not evdev, so it would be nice to have this behave a little smarter when that happens.

**Comment by kozec** [comment]
Ok, but what would smarter way to ignore all joydev devices look? :D

I can add some environment variable to toggle that skip, but I'm not entirely sure I understand issue here. Do you have gamepad that works only with joydev?

**Comment by kozec** [comment]
I've added check for two environment variables:
 - `XINPUT_NO_IGNORE_JS` will enable use of js devices 
 - `XINPUT_IGNORE_EVDEV` will _disable_ event devices.
