### ISSUE TITLE
Can't get this to work at all...

### ISSUE THREAD

**Issue by bryanwillis7** [kozec/dumbxinputemu#12]
Tried copying the two DLL files and putting them right next to "NieRAutomata.exe". The last step though I didn't quite understand.

"if you are using WINE, don't forget to add DLL override(s) and set them to 'native'"

For this I opened winecfg and under libraries I typed in "xinput1_3" and "xinput9_1_0" in the "New override for library" area. Sorry if this is completely off. It was my best guess as to what this step meant.

**Comment by kozec** [comment]
Yes, what you did was correct. Also, make sure that you are using 64bit libraries, as Nier is 64bit game.

**Comment by bryanwillis7** [comment]
What 64bit libraries do I use here? I thought all I do is literally drag your files from the 64 bit folder over to the game folder, and then it's just supposed to work?

**Comment by bryanwillis7** [comment]
Finally got this to work. I didn't realize you were supposed to run your "sc-controller" program with the xbox configuration selected while also using these .dll files. 

Anyways, it all works. You may want to mention in the description that this works with your sc-controller program. Otherwise you might get more idiots like me getting lost and frustrated

**Comment by kozec** [comment]
It works with other controllers as well, just Steam Controller is an exception in this case :)
