### ISSUE TITLE
blocked threads

### ISSUE THREAD

**Issue by y-salnikov** [kozec/dumbxinputemu#13]
Any game or program hang in infinite loop when trying to load dll.
Fresh prefix with wine-3.1 wow64:
$WINE simpleXbox360controller.exe 
002d:err:ntdll:RtlpWaitForCriticalSection section 0x7bce3a00 "../../../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 002d, blocked by 0009, retrying (60 sec)
002e:err:ntdll:RtlpWaitForCriticalSection section 0x7bce3a00 "../../../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 002e, blocked by 0009, retrying (60 sec)
002f:err:ntdll:RtlpWaitForCriticalSection section 0x7bce3a00 "../../../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 002f, blocked by 0009, retrying (60 sec)

I have tried dlls from release and self-compiled as well with same result.

**Comment by kozec** [comment]
I don't think dumbxinputemu can do that...  What's `simpleXbox360controller.exe` and where can I get it?

**Comment by y-salnikov** [comment]
http://pila.fr/wordpress/wp-content/uploads/SimpleXbox360ControllerTester.zip it's qt-based Xinput tester. Found link in your comment in previous issue https://github.com/kozec/dumbxinputemu/issues/2#issuecomment-319093969.
Same error messages pop up with any game after i place dlls.

**Comment by kozec** [comment]
Ok, I have to retract my previous statement, dumbxinputemu can do that, but only with Wine >3.0

**Comment by kozec** [comment]
(watch me pretending I know what am I doing...)
