### ISSUE TITLE
0.3.2 no longer works in Castle Crashers with WINE 3.2

### ISSUE THREAD

**Issue by psy-q** [kozec/dumbxinputemu#15]
I think there is a regression in 0.3.2. I've been using 0.3.1 to play the ancient title Castle Crashers via Steam. This used to work extremely well. But with 0.3.2 no Xbox-type controllers are detected anymore. Whatever else WINE is offering is detected instead, resulting in wrong button mapping (e.g. the game thinks the physical button X is button A).

Switching back to 0.3.1 reliably works every time.

I've been racking my brain for a while trying to figure out why this doesn't work, I've made a new WINE prefix, even tried inside of POL and everything :)

What can I provide that would help find the root of the issue?

**Comment by kozec** [comment]
> What can I provide that would help find the root of the issue?

Any other game that shows same problem, so I don't have to buy Castle Crashers just to test it :)

**Comment by psy-q** [comment]
On Fri, 02 Mar 2018 14:16:24 -0800
kozec <notifications@github.com> wrote:

> > What can I provide that would help find the root of the issue?  
> 
> Any other game that shows same problem, so I don't have to buy Castle
> Crashers just to test it :)
> 

Hmm, makes sense! Do you have a list of what games you have? Then I can
compare with mine and pick some likely candidates.

**Comment by kozec** [comment]
@psy-q Sorry, I removed that comment as I found that my brother has it. It should be possible to "family share" it.

**Comment by psy-q** [comment]
Ah great, then let's wipe the history of this issue clean :)

**Comment by kozec** [comment]
So, it looks like it's OK for game to _not_ initialize XInput and still query for devices after, assuming this thing works normally :)

Can you try it with current git checkout or this build? [build-943a0b6.tar.gz](https://github.com/kozec/dumbxinputemu/files/1778238/build-943a0b6.tar.gz)

**Comment by kozec** [comment]
Ok, this one should work without freezing newer Wine - 
[build-670df98.tar.gz](https://github.com/kozec/dumbxinputemu/files/1778247/build-670df98.tar.gz)

**Comment by psy-q** [comment]
That build works perfectly, thanks a million! I'll test with Pinball FX2 too since that was a game that really didn't enjoy the 0.3.2 DLL.

**Comment by kozec** [comment]
Great, thanks for confirmation :)

I'll check what else I fixed by accident and make new release.

**Comment by psy-q** [comment]
Awesome :)  I've been using dumbxinputemu for great glory and success for quite some time now, I'd buy you a beer if I could. Do you have a donation account somewhere?

**Comment by kozec** [comment]
Yeah, I have it listed in READMES for all (two) my other projects, so it's not so easy to found :)

https://github.com/kozec/sc-controller#like-what-im-doing

**Comment by psy-q** [comment]
Gneh, I was too stupid to look there! Just signed up, cheers :)
