### ISSUE TITLE
Not working with brawlhalla steam ?

### ISSUE THREAD

**Issue by LelouBil** [kozec/dumbxinputemu#6]
Hey,
I'm using this with sc-controller and the Xbox controller profile
I installed Brawlhalla and steam via playonlinux and i copied the dlls next to Brawlhalla.exe but when i launch the game(either via the exe or via Steam) it doesn't recognize any controller.
Can someone help me with that ?

**Comment by kozec** [comment]
It appears to run on Adobe Air, so there is good chance it doesn't use xinput at all. On related note, how did you managed to get that thing running at all?

**Comment by LelouBil** [comment]
I can use x360ce to play it with generic controllers on windows, so this means it uses xinput right ?
And I justed used playonlinux with the required libraries and wine 2.19-staging, I lag a little bit sometimes but nothing that prevents me from playing correctly.

**Comment by LelouBil** [comment]
bump ?

**Comment by kozec** [comment]
Sorry, nothing much to report, I was never able to run that game with wine.

**Comment by kozec** [comment]
There is fix that may help with some games in [last release](https://github.com/kozec/dumbxinputemu/releases/tag/v0.3.3). I'm not sure if it will help with Brawlhalla, but it may be worth trying.

**Comment by charlydelta** [comment]
Doesn't work for me either; however, I am using an xbone controller, I am not even sure if this is supported by dumbxinputemu

> On related note, how did you managed to get that thing running at all?

I just installed it using Lutris, I didn't even change a thing. Should be pretty straight forward. Why doesn't it work for you, what's the problem?

> There is fix that may help with some games in last release. I'm not sure if it will help with Brawlhalla, but it may be worth trying.

Tried the most recent release of no avail

I am rather inexperienced with controller setups in wine, so I don't know if this helps, but the developer opened [this thread on steam](https://steamcommunity.com/app/291550/discussions/0/619574421632224271/) where he talks about x360ce. So it looks like it should work, right?

**Comment by kozec** [comment]
> Doesn't work for me either; however, I am using an xbone controller, I am not even sure if this is supported by dumbxinputemu

I'd say that level of support is "you may be first person trying that ever" :)

x360ce and dumbxinputemu works in same way, _theoretically_. But I haven tried to run Brawhalla in Lutris, only with POL and native. Which wine version are you using there?

**Comment by charlydelta** [comment]
> I'd say that level of support is "you may be first person trying that ever" :)

Oh cheez I love beta testing :D

> Which wine version are you using there?

It worked long ago with 2.21-staging, and it runs now with 3.3-staging and 3.3-staging-pba. Tried them all, it works great. Don't know what else I could provide which may be of use for you. I'm on Debian stretch, the latest Lutris version, using the default winesteam installer. Worked flawlessly.

**Comment by kozec** [comment]
By the way, looking at that thread, that's a long list of supported devices. Are we sure that brawlhalla uses XInput in the 1st place?

**Comment by charlydelta** [comment]
> By the way, looking at that thread, that's a long list of supported devices. Are we sure that brawlhalla uses XInput in the 1st place?

Like I already said, I have actually no idea about controller-related stuff in Wine. I just found that while searching for a solution and thought it might be of use. I don't even know what XInput does or what the alternatives would be :(

**Comment by kozec** [comment]
People, I've got it 8-)

Basically, Brawhalla is only game in known universe actually using xinput1_**4**. Everything else uses either 1.3 or 9.1. I've added 32bit xinput1_4.dll to [tarball for latest release.](https://github.com/kozec/dumbxinputemu/releases/tag/v0.3.3)

**Comment by charlydelta** [comment]
You're awesome, thank you so much for that blazing fast fix! I can confirm that it works with Lutris using an XBox One controller.

**Comment by kozec** [comment]
Great, thanks for the confirmation :)
